import type { CertificationTestCase, TravellerDetail } from "./types";

// Test case definitions matching TBO requirements

const CASE_1: CertificationTestCase = {
  caseNumber: 1,
  caseName: "Domestic Trip - 1 Adult",
  tripType: "domestic",
  adultCount: 1,
  origin: "DEL",
  destination: "BOM",
  startDate: "2026-07-25",
  endDate: "2026-08-01",
  planCategory: 1,
  planType: 1,
  planCoverage: 4,
  travellers: [
    {
      FirstName: "Rajesh",
      LastName: "Kumar",
      DateOfBirth: "2001-06-15",
      Email: "rajesh.kumar@example.com",
      PhoneNumber: "+91-9876543210",
      Passport: "H9876543",
      Nationality: "IN",
      Title: "Mr",
      Gender: "1",
      BeneficiaryName: "Rajesh Kumar",
      RelationShipToInsured: "Self",
      RelationToBeneficiary: "Self",
      AddressLine1: "123 Main Street",
      AddressLine2: "Apartment 4B",
      CityCode: "DEL",
      CountryCode: "IN",
      PinCode: "110001",
    },
  ],
};

const CASE_2: CertificationTestCase = {
  caseNumber: 2,
  caseName: "Domestic Trip - 2 Adults",
  tripType: "domestic",
  adultCount: 2,
  origin: "DEL",
  destination: "GOA",
  startDate: "2026-08-01",
  endDate: "2026-08-08",
  planCategory: 1,
  planType: 1,
  planCoverage: 4,
  travellers: [
    {
      FirstName: "Arjun",
      LastName: "Sharma",
      DateOfBirth: "1989-03-15",
      Email: "arjun.sharma@example.com",
      PhoneNumber: "+91-9876543211",
      Passport: "H1234567",
      Nationality: "IN",
      Title: "Mr",
      Gender: "1",
      BeneficiaryName: "Arjun Sharma",
      RelationShipToInsured: "Self",
      RelationToBeneficiary: "Self",
      AddressLine1: "456 Park Avenue",
      AddressLine2: "Suite 200",
      CityCode: "DEL",
      CountryCode: "IN",
      PinCode: "110002",
    },
    {
      FirstName: "Priya",
      LastName: "Singh",
      DateOfBirth: "1970-07-22",
      Email: "priya.singh@example.com",
      PhoneNumber: "+91-9876543212",
      Passport: "H7654321",
      Nationality: "IN",
      Title: "Mrs",
      Gender: "2",
      BeneficiaryName: "Priya Singh",
      RelationShipToInsured: "Spouse",
      RelationToBeneficiary: "Spouse",
      AddressLine1: "456 Park Avenue",
      AddressLine2: "Suite 200",
      CityCode: "DEL",
      CountryCode: "IN",
      PinCode: "110002",
    },
  ],
};

const CASE_3: CertificationTestCase = {
  caseNumber: 3,
  caseName: "Non-US Trip - 1 Adult",
  tripType: "non-us",
  adultCount: 1,
  origin: "DEL",
  destination: "BKK",
  startDate: "2026-09-10",
  endDate: "2026-09-17",
  planCategory: 1,
  planType: 1,
  planCoverage: 4,
  travellers: [
    {
      FirstName: "Vikram",
      LastName: "Patel",
      DateOfBirth: "1992-11-08",
      Email: "vikram.patel@example.com",
      PhoneNumber: "+91-9876543213",
      Passport: "H4567890",
      Nationality: "IN",
      Title: "Mr",
      Gender: "1",
      BeneficiaryName: "Vikram Patel",
      RelationShipToInsured: "Self",
      RelationToBeneficiary: "Self",
      AddressLine1: "789 Beach Road",
      AddressLine2: "Building C",
      CityCode: "BOM",
      CountryCode: "IN",
      PinCode: "400001",
    },
  ],
};

const CASE_4: CertificationTestCase = {
  caseNumber: 4,
  caseName: "Non-US Trip - 2 Adults",
  tripType: "non-us",
  adultCount: 2,
  origin: "BOM",
  destination: "SIN",
  startDate: "2026-10-05",
  endDate: "2026-10-12",
  planCategory: 1,
  planType: 1,
  planCoverage: 4,
  travellers: [
    {
      FirstName: "Anil",
      LastName: "Gupta",
      DateOfBirth: "1988-06-30",
      Email: "anil.gupta@example.com",
      PhoneNumber: "+91-9876543214",
      Passport: "H2345678",
      Nationality: "IN",
      Title: "Mr",
      Gender: "1",
      BeneficiaryName: "Anil Gupta",
      RelationShipToInsured: "Self",
      RelationToBeneficiary: "Self",
      AddressLine1: "321 Commerce Street",
      AddressLine2: "Floor 5",
      CityCode: "BOM",
      CountryCode: "IN",
      PinCode: "400002",
    },
    {
      FirstName: "Neha",
      LastName: "Iyer",
      DateOfBirth: "1969-12-18",
      Email: "neha.iyer@example.com",
      PhoneNumber: "+91-9876543215",
      Passport: "H8765432",
      Nationality: "IN",
      Title: "Mrs",
      Gender: "2",
      BeneficiaryName: "Neha Iyer",
      RelationShipToInsured: "Spouse",
      RelationToBeneficiary: "Spouse",
      AddressLine1: "321 Commerce Street",
      AddressLine2: "Floor 5",
      CityCode: "BOM",
      CountryCode: "IN",
      PinCode: "400002",
    },
  ],
};

const CASE_5: CertificationTestCase = {
  caseNumber: 5,
  caseName: "US/Canada Trip - 2 Adults",
  tripType: "us-canada",
  adultCount: 2,
  origin: "DEL",
  destination: "YYZ",
  startDate: "2026-11-20",
  endDate: "2026-11-27",
  planCategory: 1,
  planType: 1,
  planCoverage: 4,
  travellers: [
    {
      FirstName: "Rahul",
      LastName: "Desai",
      DateOfBirth: "1987-09-25",
      Email: "rahul.desai@example.com",
      PhoneNumber: "+91-9876543216",
      Passport: "H5678901",
      Nationality: "IN",
      Title: "Mr",
      Gender: "1",
      BeneficiaryName: "Rahul Desai",
      RelationShipToInsured: "Self",
      RelationToBeneficiary: "Self",
      AddressLine1: "654 Tech Park",
      AddressLine2: "Unit 10",
      CityCode: "BOM",
      CountryCode: "IN",
      PinCode: "400003",
    },
    {
      FirstName: "Anjali",
      LastName: "Nair",
      DateOfBirth: "1968-04-14",
      Email: "anjali.nair@example.com",
      PhoneNumber: "+91-9876543217",
      Passport: "H9012345",
      Nationality: "IN",
      Title: "Mrs",
      Gender: "2",
      BeneficiaryName: "Anjali Nair",
      RelationShipToInsured: "Spouse",
      RelationToBeneficiary: "Spouse",
      AddressLine1: "654 Tech Park",
      AddressLine2: "Unit 10",
      CityCode: "BOM",
      CountryCode: "IN",
      PinCode: "400003",
    },
  ],
};

export const ALL_TEST_CASES: CertificationTestCase[] = [
  CASE_1,
  CASE_2,
  CASE_3,
  CASE_4,
  CASE_5,
];

export function getTestCaseByNumber(caseNumber: number): CertificationTestCase | undefined {
  return ALL_TEST_CASES.find((tc) => tc.caseNumber === caseNumber);
}

export function getTestCasesByType(tripType: "domestic" | "non-us" | "us-canada"): CertificationTestCase[] {
  return ALL_TEST_CASES.filter((tc) => tc.tripType === tripType);
}

export function getTestCasesByAdultCount(count: 1 | 2): CertificationTestCase[] {
  return ALL_TEST_CASES.filter((tc) => tc.adultCount === count);
}
